from abc import ABC, abstractmethod
from typing import List, Dict
from src.common.types import FrameMetadata, AssociationState
from src.association.types import AssociationEvent
from src.behavior.types import BehaviorFlag

class BehaviorRule(ABC):
    """Abstract base class for independent behavior template rule plugins."""

    @abstractmethod
    def evaluate(
        self,
        track_id: int,
        event_history: List[AssociationEvent]
    ) -> List[BehaviorFlag]:
        """Evaluates historical events for a specific customer track to match patterns.

        Args:
            track_id: Person tracking identifier.
            event_history: Time-ordered list of association events for the track.

        Returns:
            A list of BehaviorFlag alerts generated by this rule.
        """
        pass


class BaseBehaviorEngine(ABC):
    """Abstract base class defining the contract for analyzing customer actions."""

    @abstractmethod
    def analyze(
        self,
        frame_metadata: FrameMetadata,
        association_events: List[AssociationEvent]
    ) -> List[BehaviorFlag]:
        """Analyzes historical track states and new events to detect suspicious actions.

        Args:
            frame_metadata: Current frame tracks and keypoints.
            association_events: New association events generated in the current frame step.

        Returns:
            A list of BehaviorFlag objects containing flagged actions.

        Raises:
            PipelineError: If event tracking or sequence evaluation fails.
        """
        pass
